In [31]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
#une partie de la liste
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [14]:
slice_of_arr[:]=99
slice_of_arr


array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[0][1]

10

In [25]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [26]:
arr>5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [27]:
bool_arr = arr>5

In [28]:
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [30]:
arr[bool_arr]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])